### PR TITLE
Bugfix/repair livemode

### LINKED ISSUE #50: Bugfix: App crashes when entering Live Mode
In current master_lab version (commit 6353e0b37d3d41c91dcc976c985ac59eaf0f0afe, but probably earlier versions as well) the app crashes when switching to "Live Mode" due to a NullPointerException:

java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setTitle(int)' on a null object reference

LiveModeInteraction.java:57

### PR DESCRIPTION
**Pull request by anykeyjunkie**
fixes #50

### CODE REVIEW

File: app/src/main/java/seemoo/fitbit/fragments/MainFragment.java [hunk 1]
```diff
@@ -526,22 +526,21 @@ public void buttonSetDate() {
...
+            if (!interactions.getAuthenticated()) {
+                interactions.intAuthentication();
             }
-        });
-        builder.show();
+            interactions.intLiveModeEnable();
+        }
+    }
+
+    public boolean isLiveMoveActive(){
```
Comment (stekreis) [inline app/src/main/java/seemoo/fitbit/fragments/MainFragment.java]: typo "Move": isLiveModeActive
